command /survival:
    trigger:
        execute console command "mv tp %player% survival"
        send "&aTeleporting you to the &2Survival &aworld..."

command /hworld:
    trigger:
        execute console command "mv tp %player% hworld"
        send "&aTeleporting you to the &2HWorld &aworld..."

command /zworld:
    trigger:
        execute console command "mv tp %player% zworld"
        send "&aTeleporting you to the &2ZWorld &aworld..."
